plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.yusufekremunlu.easyway'
    compileSdk 34
    signingConfigs {
        config {
            keyAlias 'developer'
            keyPassword '12345678'
            storeFile file('C:\\Users\\yusuf\\Desktop\\Projects\\EasyWay\\developer-kits.jks')
            storePassword '12345678'
        }
    }
    defaultConfig {
        applicationId "com.yusufekremunlu.easyway"
        minSdk 21
        targetSdk 34
        versionCode 8
        versionName "1.8"
        resConfigs "en", "zh-rCN"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            signingConfig signingConfigs.config
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.config
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    viewBinding {
        enabled = true
    }

    dataBinding {
        enabled = true
    }

}

def fragment_version = "1.6.1"
def nav_version = "2.7.2"
def bom_version = "32.1.0"
def room_version = "2.5.2"
def view_model_version = "2.6.2"
def lifecycle_extension_version = "2.2.0"
def google_play_services_version = "20.7.0"
def retrofit_version = "2.9.0"
def gson_converter_version = "2.9.0"
def glide_version = "4.12.0"
def picasso_version = "2.8"
def volley_version = "1.2.1"
def camerax_version = "1.4.0-alpha01"
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

    // Java language implementation
    implementation "androidx.fragment:fragment:$fragment_version"
    // Java language implementation
    //noinspection GradleDependency
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    //noinspection GradleDependency
    implementation "androidx.navigation:navigation-ui:$nav_version"
    // Firebase implementation
    implementation platform("com.google.firebase:firebase-bom:$bom_version")
    implementation 'com.google.firebase:firebase-auth'
    // ViewModel implementation
    implementation "androidx.lifecycle:lifecycle-viewmodel:$view_model_version"
    implementation "androidx.lifecycle:lifecycle-extensions:$lifecycle_extension_version"
    //Google Play services
    implementation "com.google.android.gms:play-services-auth:$google_play_services_version"
    //Retrofit
    implementation "com.squareup.retrofit2:retrofit:$retrofit_version"
    implementation "com.squareup.retrofit2:converter-gson:$gson_converter_version"
    //Glide
    implementation "com.github.bumptech.glide:glide:$glide_version"
    annotationProcessor "com.github.bumptech.glide:compiler:$glide_version"
    //Room
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    //Picasso
    implementation "com.squareup.picasso:picasso:$picasso_version"
    //Volley
    implementation "com.android.volley:volley:$volley_version"
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))
    //Google ML Kit
    implementation 'com.google.mlkit:barcode-scanning:17.2.0'
    implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.0'
    // The following line is optional, as the core library is included indirectly by camera-camera2
    implementation "androidx.camera:camera-core:${camerax_version}"
    implementation "androidx.camera:camera-camera2:${camerax_version}"
    // If you want to additionally use the CameraX Lifecycle library
    implementation "androidx.camera:camera-lifecycle:${camerax_version}"
    // If you want to additionally use the CameraX VideoCapture library
    implementation "androidx.camera:camera-video:${camerax_version}"
    // If you want to additionally use the CameraX View class
    implementation "androidx.camera:camera-view:${camerax_version}"
    // If you want to additionally add CameraX ML Kit Vision Integration
    implementation "androidx.camera:camera-mlkit-vision:${camerax_version}"
    // If you want to additionally use the CameraX Extensions library
    implementation "androidx.camera:camera-extensions:${camerax_version}"
}
